title: Neo Framework
description: >
    The PHP Framework For Web Peasants
baseurl: ""
url: "https://neo-framework.github.io"

twitter_username: younishd
github_username: neo-framework
copyright: "2016-2017 YouniS Bensalah"

markdown: kramdown
